CREATE TABLE AUTHORS
( ID              NUMBER(10)   NOT NULL
, LASTNAME        VARCHAR2(50) NOT NULL
, INITIALS        VARCHAR2(10)
, FIRSTNAME       VARCHAR2(30)
, LASTNAME_PREFIX VARCHAR2(30)
, DATE_OF_BIRTH   VARCHAR2(10)
, NATIONALITY     VARCHAR2(3)
, CONSTRAINT AUTHOR_PK PRIMARY KEY (ID)
)
/

CREATE TABLE BOOKS
( ID        NUMBER(10)   NOT NULL
, ISBN      VARCHAR2(15) NOT NULL
, TITLE     VARCHAR2(100) NOT NULL
, SUBTITLE  VARCHAR2(100)
, YEAR      NUMBER(4)
, AUTHOR_ID NUMBER(10) NOT NULL
, CONSTRAINT BOOKS_PK PRIMARY KEY (ID)
, CONSTRAINT BOOKS_AUTHORS_FK FOREIGN KEY (AUTHOR_ID)
                              REFERENCES DEMO.AUTHORS(ID)
)
/
